#language: java
#sudo: false # faster builds
#
#after_success:
#  - bash <(curl -s https://codecov.io/bash)

language: node_js
sudo: false
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
after_success:
  - npm run codecov